name: Auto Tag on PR

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Create tag
        run: |
          # Get the current version from package.json
          VERSION=${{ steps.package-version.outputs.current-version }}
          
          # Create and push the tag
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${VERSION}" -m "Release version ${VERSION}"
          git push origin "v${VERSION}"

      - name: Add tag link to PR
        uses: actions/github-script@v6
        with:
          script: |
            const version = process.env.VERSION
            const prNumber = context.payload.pull_request.number
            const repo = context.repo
            
            await github.rest.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: prNumber,
              body: `🏷️ Created tag v${version} for this PR`
            }) 