name: Auto Tag and Publish on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-tag-and-publish:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write # Need write permissions to push commit and tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use v4
        with:
          # Fetch all history so we can check for existing tags accurately
          fetch-depth: 0
          # Check out the main branch explicitly after merge
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Use a consistent Node version
          cache: 'npm'

      - name: Install dependencies # Added dependency install for npm version etc.
        run: npm install

      - name: Get current version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Determine and Set Version
        id: set-version
        run: |
          CURRENT_VERSION=${{ steps.package-version.outputs.current-version }}
          TARGET_VERSION=$CURRENT_VERSION # Default to current version

          # Check if tag already exists
          if git rev-parse "v${CURRENT_VERSION}" >/dev/null 2>&1; then
            echo "Tag v${CURRENT_VERSION} already exists. Calculating next minor version."
            TARGET_VERSION=$(npm version --no-git-tag-version minor)
            TARGET_VERSION=${TARGET_VERSION#v}
            echo "Calculated next version: ${TARGET_VERSION}"
            # Reset package.json back temporarily
            git checkout -- package.json package-lock.json # Safer reset
          else
            echo "Tag v${CURRENT_VERSION} does not exist. Using current version."
          fi

          echo "TARGET_VERSION=${TARGET_VERSION}" >> $GITHUB_OUTPUT

      - name: Update package.json, Commit, Tag, and Push
        id: version-commit-tag-push # Added ID for potential future use
        env:
          TARGET_VERSION: ${{ steps.set-version.outputs.TARGET_VERSION }}
        run: |
          echo "Target version for update and tag: ${TARGET_VERSION}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Update package.json only if the version changed or doesn't exist yet
          if [[ "$(jq -r .version package.json)" != "${TARGET_VERSION}" ]]; then
            npm version ${TARGET_VERSION} --no-git-tag-version --no-push --allow-same-version
            echo "package.json updated to version ${TARGET_VERSION}"
            git add package.json package-lock.json || true
            git commit -m "chore: bump version to ${TARGET_VERSION}"
          else
             echo "package.json already at version ${TARGET_VERSION}. Skipping commit."
          fi

          echo "Creating Git tag v${TARGET_VERSION}"
          git tag -a "v${TARGET_VERSION}" -m "Release version ${TARGET_VERSION}"

          echo "Pushing changes (if any) and tag to origin main"
          # Push main first, then the tag
          git push origin main
          git push origin "v${TARGET_VERSION}"

          # Set output for other steps
          echo "VERSION=${TARGET_VERSION}" >> $GITHUB_ENV

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Publish to VS Code Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }} # Use secret for PAT
          TARGET_VERSION: ${{ steps.set-version.outputs.TARGET_VERSION }}
        run: |
          echo "Publishing version ${TARGET_VERSION} to VS Code Marketplace..."
          vsce publish --packagePath . # Publishes the version from package.json

      - name: Add completion comment to PR
        # Run this step even if publish fails (optional, adjust if needed)
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const version = process.env.VERSION
            if (!version) {
              console.log('VERSION environment variable not set. Skipping comment.')
              return
            }
            const prNumber = context.payload.pull_request.number
            const repo = context.repo
            
            // You might want to check the outcome of the publish step here
            // For now, just confirm the tag was created
            
            await github.rest.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: prNumber,
              body: `✅ PR was merged, version bumped to \`${version}\`. Tag \`v${version}\` created and pushed. Attempted publishing to VS Code Marketplace.`
            }) 